#include <iostream>

enum OFX_FURRY_TYPE
{

	OFX_GPU_TYPE_A,
	OFX_GPU_TYPE_B,
	OFX_GPU_TYPE_C,
	OFX_GPU_TYPE_D,
	OFX_GPU_TYPE_E,
	OFX_GPU_TYPE_F,

	OFX_BUFFER_TYPE_A,
	OFX_BUFFER_TYPE_B,
	OFX_BUFFER_TYPE_C,
	OFX_BUFFER_TYPE_D,
	OFX_BUFFER_TYPE_E,
	OFX_BUFFER_TYPE_F,
	OFX_BUFFER_TYPE_G,
	OFX_BUFFER_TYPE_H,
	OFX_BUFFER_TYPE_I,
	OFX_BUFFER_TYPE_L,
};
