#include <iostream>

enum OFX_FURRY_TYPE
{

	OFX_GPU_TYPE_A=0,
	OFX_GPU_TYPE_B=1,
	OFX_GPU_TYPE_C=2,
	OFX_GPU_TYPE_D=3,
	OFX_GPU_TYPE_E=4,
	OFX_GPU_TYPE_F=5,

	OFX_BUFFER_TYPE_A=0,
	OFX_BUFFER_TYPE_B=1,
	OFX_BUFFER_TYPE_C=2,
	OFX_BUFFER_TYPE_D=3,
	OFX_BUFFER_TYPE_E=4,
	OFX_BUFFER_TYPE_F=5,
	OFX_BUFFER_TYPE_G=6,
	OFX_BUFFER_TYPE_H=7,
	OFX_BUFFER_TYPE_I=8,
	OFX_BUFFER_TYPE_L=9,

	OFX_BUFFER_CUSTOM_MESH=10,
};
